name: make linux deploy

on:
  push:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch: { }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous build
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: clone zstd
      run: git clone https://github.com/facebook/zstd.git
    - name: make builder folder
      run: |
        cd zstd/build/cmake/
        mkdir armeabi-v7a arm64-v8a x86_64 x86

    - name: build zstd for armeabi-v7a
      run: |
        $ANDROID_HOME/cmake/3.22.1/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a zstd/build/cmake/armeabi-v7a
        make -j 8
    - uses: actions/upload-artifact@v3
      with:
        name: zstd for armeabi-v7a
        path: programs/zstdcat

    - name: build zstd for arm64-v8a
      run: |
        $ANDROID_HOME/cmake/3.22.1/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a zstd/build/cmake/arm64-v8a
        make -j 8
    - uses: actions/upload-artifact@v3
      with:
        name: zstd for arm64-v8a
        path: programs/zstdcat

    - name: build zstd for x86_64
      run: |
        $ANDROID_HOME/cmake/3.22.1/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86_64 zstd/build/cmake/x86_64
        make -j 8
    - uses: actions/upload-artifact@v3
      with:
        name: zstd for x86_64
        path: programs/zstdcat

    - name: build zstd for x86
      run: |
        $ANDROID_HOME/cmake/3.22.1/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=x86 zstd/build/cmake/x86
        make -j 8
    - uses: actions/upload-artifact@v3
      with:
        name: zstd for x86
        path: programs/zstdcat
