name: make linux deploy

on:
  push:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  pull_request:
    branch: [ "main" ]
    paths-ignore:
      - "**.md"
  workflow_dispatch: { }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous build
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: zstdcat Build
      run: |
        ls $ANDROID_HOME/cmake
        ls $ANDROID_HOME/ndk
        git clone https://github.com/facebook/zstd.git
        cd zstd/build/cmake/
        mkdir builddir/
        cd builddir/
        $ANDROID_HOME/cmake/3.10.2.4988404/bin/cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..
        make -j 8
    - uses: actions/upload-artifact@v3
      with:
        name: files
        path: /home/runner/work/files-for-deploy/files-for-deploy/zstd/build/cmake/builddir

